# Generated by Django 6.0.5 on 2026-05-24 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_aluno', models.CharField(max_length=200)),
                ('curso', models.CharField(choices=[('administracao', 'Administração'), ('enfermagem', 'Enfermagem'), ('informatica', 'Informática'), ('logistica', 'Logística'), ('ds', 'Desenvolvimento de Sistemas')], max_length=50)),
                ('ano', models.CharField(choices=[('1', '1º Ano'), ('2', '2º Ano'), ('3', '3º Ano')], max_length=1)),
                ('data', models.DateField()),
                ('descricao', models.TextField()),
                ('gravidade', models.CharField(choices=[('leve', 'Leve'), ('media', 'Média'), ('grave', 'Grave')], max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ocorrência',
                'verbose_name_plural': 'Ocorrências',
                'ordering': ['-criado_em'],
            },
        ),
    ]
