# Generated by Django 6.0.5 on 2026-05-30 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(db_index=True, max_length=20, unique=True)),
                ('nome', models.CharField(db_index=True, max_length=200)),
                ('curso', models.CharField(choices=[('administracao', 'Administração'), ('enfermagem', 'Enfermagem'), ('informatica', 'Informática'), ('logistica', 'Logística'), ('ds', 'Desenvolvimento de Sistemas')], db_index=True, max_length=50)),
                ('ano', models.PositiveSmallIntegerField(choices=[(1, '1º Ano'), (2, '2º Ano'), (3, '3º Ano')], db_index=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_index=True)),
                ('descricao', models.TextField()),
                ('gravidade', models.CharField(choices=[('leve', 'Leve'), ('media', 'Média'), ('grave', 'Grave')], db_index=True, default='leve', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ocorrencias', to='ocorrencias.aluno')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ocorrência',
                'verbose_name_plural': 'Ocorrências',
                'ordering': ['-criado_em'],
            },
        ),
    ]
